### ISSUE TITLE
When the host IP changes while running, the connection cannot be recovered automatically.

### ISSUE THREAD

**Issue by ghost** [wangyu-/UDPspeeder#323]
I was trying to run udpspeeder client on openwrt router. when WAN interface IP address changed, udpspeeder tunnel will broke and cannot be recovered automatically.
AS a useful network quality optimize tool, i think this bug isn't acceptable for normal users. and it's low level error.
I hope will fix future. or developer should accept suited PR from others.

**Comment by wangyu-** [comment]
At least 80% tunnels in the world doesn't support change of WAN ip.

You can write a script to kill udpspeeeder when your WAN ip is changed.

**Comment by wangyu-** [comment]
udp2raw supports changing of wan IP, and even changing of interface:

```
before your interface is down.
CLIENT----->session1-->u->udp2raw(eth0,202.96.x.x)------------>udp2raw----session1------->SERVER

After eth0 is down:
CLIENT----->session1-->udp2raw(wlan0,210.82.x.x)-------------->udp2raw---session1(recovered)------->SERVER
```

You can chain udp2raw into you topology:

```
CLIENT--->udpspeeder->udp2raw-------------------------------------->udp2raw-->udpspeeder---->SERVER
```

Then your problem is solved, and it works even better (all existing sessions will not lost).

I don't plan to re-implement this feature in UDPspeeder, since you can get the same effect by chainning udp2raw.
